import React from "react";

const NFTDescription = () => {
  return (
    <div className="text-center mb-6 sm:mb-8 md:mb-10">
      <h1 className="font-zen-dots text-2xl sm:text-3xl md:text-4xl font-normal leading-8 sm:leading-10 pt-6 sm:pt-8 md:pt-10 mb-2 px-4">
        Popular NFT's Generated by Artists
      </h1>

      <p className="font-inter text-xs sm:text-sm md:text-base lg:text-lg font-normal leading-5 sm:leading-6 md:leading-7 text-center mx-auto opacity-80 px-4 pb-3 sm:pb-5">
        3dotlink's AI integration is a game-changer in the NFT art world. It
        offers a powerful canvas for artists to redefine art creation and
        innovation while preserving cultural art in an entirely new format. With
        this platform, the convergence of human ingenuity and AI technology is
        set to redefine the boundaries of artistic expression and creative
        possibilities, ushering in a digital art renaissance.
      </p>
    </div>
  );
};

export default NFTDescription;
